### ISSUE TITLE
Empty docs

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/ml-core#18]
The built documentation is empty.

https://ml-core.readthedocs.io/en/latest/

**Comment by vmarkovtsev** [comment]
Stable build failed: https://readthedocs.org/projects/ml-core/builds/9083658/

**Comment by vmarkovtsev** [comment]
@Guillemdb Still empty: https://ml-core.readthedocs.io/en/latest/

**Comment by Guillemdb** [comment]
Looks like it works now. Do you want me to add something else to the docs?

**Comment by vmarkovtsev** [comment]
Nope for now. Thanks! Done.
